version: '3'

services:

    siridb:
        build: 
            context: ./siridb
        hostname: siridb
        container_name: siridb
        restart: always        
        ports: 
        - 9000:9000
        - 9010:9010
        - 9020:9020
        - 9080:8080
        networks:
        - tp-net

    siridb-admin:
        build: 
            context: ./siridb-admin
        hostname: siridb-admin
        container_name: siridb-admin
        # restart: always     
        ports: 
        - 9180:8080
        depends_on:
        - siridb
        networks:
        - tp-net

    rethinkdb:
        image: rethinkdb:2.4.1
        hostname: rethinkdb
        container_name: rethinkdb
        restart: always
        ports: 
        - 8080:8080
        volumes:
        - $PWD:/data/r1
        networks:
        - tp-net

    backend-tiempos:
        build: 
            context: ./backend-tiempos
        environment: 
        - HOST=siridb
        hostname: backend-tiempos
        container_name: backend-tiempos
        restart: always     
        ports: 
        - 3001:3001
        depends_on:
        - siridb
        networks:
        - tp-net

    backend-tiempos:
        build: 
            context: ./backend-tiempos
        environment: 
        - HOST=siridb
        hostname: backend-tiempos
        container_name: backend-tiempos
        restart: always     
        ports: 
        - 3001:3001
        depends_on:
        - siridb
        networks:
        - tp-net

    backend-dispositivos:
        build: 
            context: ./backend-dispositivos
        environment: 
        - HOST=rethinkdb
        hostname: backend-dispositivos
        container_name: backend-dispositivos
        restart: always     
        ports: 
        - 3000:3000
        depends_on:
        - rethinkdb
        networks:
        - tp-net
    
networks:
    tp-net:
        driver: bridge