version: '3'

services:

    rethinkdb:
        image: rethinkdb:2.4.1
        hostname: rethinkdb
        container_name: rethinkdb
        restart: always
        ports: 
        - 8081:8080
        volumes:
        - $PWD:/data/r1
        networks:
        - tp-net

    backend-dispositivos:
        build: 
            context: ./backend-dispositivos
        environment: 
        - HOST=rethinkdb
        hostname: backend-dispositivos
        container_name: backend-dispositivos
        restart: always     
        ports: 
        - 3000:3000
        depends_on:
        - rethinkdb
        - mosquitto
        networks:
        - tp-net

    mosquitto:
        image: eclipse-mosquitto:1.6.12
        hostname: mosquitto
        container_name: mosquitto
        restart: always
        volumes:
        - ./mosquitto/:/mosquitto/
        expose:
        - "1883"
        - "9001"
        ports: 
        - 1883:1883
        - 9001:9001
        depends_on:
        - rethinkdb
        networks:
        - tp-net

    frontend-dispositivos:
        build: 
            context: ./frontend
        hostname: frontend
        container_name: frontend
        restart: always     
        ports: 
        - 5000:5000
        depends_on:
        - rethinkdb
        - mosquitto
        - backend-dispositivos
        networks:
        - tp-net

networks:
    tp-net:
        driver: bridge