FROM siridb/siridb-admin:latest
ENTRYPOINT ["/usr/local/bin/siridb-admin", "-u", "sa", "-p", "siri", "-s", "siridb", "new-database", "-d", "iot", "-t", "ms"]

# siridb-admin -u sa -p siri -s siridb01.foo.local new-database -d dbexample -t s